export const NEW_CLIENT_REQUEST = 'NEW_CLIENT_REQUEST';
export const NEW_CLIENT_SUCCESS = 'NEW_CLIENT_SUCCESS';
export const NEW_CLIENT_FAILURE = 'NEW_CLIENT_FAILURE';
export const ADD_CONNECTION_TYPE = 'ADD_CONNECTION_TYPE';
